services:
  youtube-analysis:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env       # <-- Thêm dòng này để load biến trong file .env
    volumes:
      - ./downloads:/app/downloads
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN

  youtube-analysis-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env      
    volumes:
      - .:/app
      - /app/node_modules
      - ./downloads:/app/downloads
    profiles:
      - dev
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
